[project]
name = "python"
version = "0.1.0"
description = "WebAP Captcha"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
    "ai-edge-litert==1.4.0",
    "pillow==11.3.0",
    "requests==2.32.5",
]
